[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = huge_app.csv ; MỞ RỘNG PHÂN VÙNG APP LÊN 3MB
; Khai báo kiến trúc lai (ESP-IDF làm lõi chính, Arduino làm module)
framework = arduino, espidf
monitor_speed = 115200
; THÊM DÒNG NÀY: Hạ xung nhịp CPU từ 240MHz xuống 160MHz để giảm 30% lượng nhiệt tỏa ra
board_build.f_cpu = 160000000L

; BỔ SUNG 2 DÒNG NÀY ĐỂ NGĂN TERMINAL ÉP CHIP VÀO CHẾ ĐỘ NẠP
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    lvgl/lvgl @ ~8.3.11
    bblanchon/ArduinoJson @ ^6.21.3

; Bê nguyên toàn bộ build_flags từ mã cũ của bạn sang đây
build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=21
    -D TFT_RST=22
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT8=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
    -D TFT_RGB_ORDER=TFT_BGR
    -D DISABLE_ALL_LIBRARY_WARNINGS
    ; --- CẤU HÌNH LVGL (KÍCH HOẠT KHÔNG CẦN lv_conf.h) ---
    -D LV_CONF_SKIP=1
    -D LV_COLOR_DEPTH=16
    -D LV_TICK_CUSTOM=1
    -D LV_FONT_MONTSERRAT_14=1 ; Font mặc định của LVGL